In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import numpy as np

https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

### **Quickstart**

##### **Loading the Data**

In [3]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [4]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


##### **Creating Models**

In [5]:
#Define the model 

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(), 
            nn.Linear(512,10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
    
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


##### **Optimizing the Model Parameters**

In [6]:
# Define the loss function and optimizers 

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-3)

In [7]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    
    for batch, (X, y) in enumerate(dataloader):

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [8]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
        test_loss /= num_batches
        correct /= size 
        print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [9]:
epochs = 5 
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
loss: 2.296834  [   64/60000]
loss: 2.288705  [ 6464/60000]
loss: 2.271116  [12864/60000]
loss: 2.264653  [19264/60000]
loss: 2.244174  [25664/60000]
loss: 2.210268  [32064/60000]
loss: 2.213513  [38464/60000]
loss: 2.177006  [44864/60000]
loss: 2.167622  [51264/60000]
loss: 2.137719  [57664/60000]
Test Error: 
 Accuracy: 54.4%, Avg loss: 2.134293 

Epoch 2
-------------------------------
loss: 2.142168  [   64/60000]
loss: 2.134889  [ 6464/60000]
loss: 2.076681  [12864/60000]
loss: 2.092041  [19264/60000]
loss: 2.046876  [25664/60000]
loss: 1.978286  [32064/60000]
loss: 2.000742  [38464/60000]
loss: 1.919197  [44864/60000]
loss: 1.919850  [51264/60000]
loss: 1.842100  [57664/60000]
Test Error: 
 Accu

### **Tensors**

In [10]:
# Initializing a tensor directly from data 

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

# Initializing a tensor directly from NumPy array 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [11]:
# Attributes of a Tensor

tensor = torch.rand(3,4)

# Get the shape 
print(tensor.shape)

# Get the data type 
print(tensor.dtype)

# Get the device 
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [12]:
# Tensor Operations 

# To join tensors 
t1 = torch.cat([tensor, tensor, tensor], dim = 1)

print(t1)

tensor([[0.6497, 0.7020, 0.4748, 0.4863, 0.6497, 0.7020, 0.4748, 0.4863, 0.6497,
         0.7020, 0.4748, 0.4863],
        [0.5188, 0.3244, 0.0479, 0.0493, 0.5188, 0.3244, 0.0479, 0.0493, 0.5188,
         0.3244, 0.0479, 0.0493],
        [0.9611, 0.2432, 0.1462, 0.9293, 0.9611, 0.2432, 0.1462, 0.9293, 0.9611,
         0.2432, 0.1462, 0.9293]])


In [13]:
# Arithmetic Operations 

# Compute the matrix multiplication between two tensors in three diffferent ways

print(tensor)

y1 = tensor @ tensor.T  
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T,out=y3)

print(y1, y2, y3)

# Compute the element-wise product 

z1 = tensor * tensor 
z2 = tensor.mul(tensor)

print(z1, z2)


tensor([[0.6497, 0.7020, 0.4748, 0.4863],
        [0.5188, 0.3244, 0.0479, 0.0493],
        [0.9611, 0.2432, 0.1462, 0.9293]])
tensor([[1.3769, 0.6116, 1.3165],
        [0.6116, 0.3791, 0.6303],
        [1.3165, 0.6303, 1.8678]]) tensor([[1.3769, 0.6116, 1.3165],
        [0.6116, 0.3791, 0.6303],
        [1.3165, 0.6303, 1.8678]]) tensor([[1.3769, 0.6116, 1.3165],
        [0.6116, 0.3791, 0.6303],
        [1.3165, 0.6303, 1.8678]])
tensor([[0.4221, 0.4929, 0.2254, 0.2365],
        [0.2691, 0.1052, 0.0023, 0.0024],
        [0.9237, 0.0592, 0.0214, 0.8635]]) tensor([[0.4221, 0.4929, 0.2254, 0.2365],
        [0.2691, 0.1052, 0.0023, 0.0024],
        [0.9237, 0.0592, 0.0214, 0.8635]])


### **Datasets & DataLoaders**

In [14]:
training_data = datasets.FashionMNIST(
    root = "data",         # path where the train/test data is stored
    train = True,          # specifies training or test dataset
    download = True, 
    transform = ToTensor() # feature and label transformations
)

test_data = datasets.FashionMNIST(
    root = "data",         # path where the train/test data is stored
    train = False,          # specifies training or test dataset
    download = True, 
    transform = ToTensor() # feature and label transformations
)


##### **Preparing your data for training with DataLoaders**



In [15]:
# The Dataset retrieves our dataset’s features and labels one sample at a time. While training a model, we typically want to pass samples in “minibatches”, reshuffle the data at every epoch to reduce model overfitting, and use Python’s multiprocessing to speed up data retrieval.

train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

# We have loaded that dataset into the DataLoader and can iterate through the dataset as needed. Each iteration below returns a batch of train_features and train_labels (containing batch_size=64 features and labels respectively). Because we specified shuffle=True, after we iterate over all batches the data is shuffled (for finer-grained control over the data loading order, take a look at Samplers).

# Display image and label.
train_features, train_labels = next(iter(train_dataloader))
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")


Feature batch shape: torch.Size([64, 1, 28, 28])
Labels batch shape: torch.Size([64])


### **Transforms**

Lambda transforms apply any user-defined lambda function. Here, we define a function to turn the integer into a one-hot encoded tensor. It first creates a zero tensor of size 10 (the number of labels in our dataset) and calls scatter_ which assigns a value=1 on the index as given by the label y.

In [16]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)